### ISSUE TITLE
Requestor response in private message

### ISSUE THREAD

**Issue by MJ-Deepshadow** [krbz999/requestor#16]
Hello,
I did not understand how I could configure so that the result of the dice roll does not appear in the chat but just in private in response to the GM (but maybe it's not possible).
Thank you for your answer.

**Comment by MJ-Deepshadow** [comment]
I 'm using Requestor in a macro of my own, calling for roll test, and I wish have the answer of the request (when my player click the button of the request) to be only read by me and the player (not the others). Don't know if this is possible directly in Requestor :)

**Comment by krbz999** [comment]
If it is a fully custom method you are using, not the one provided as-is by the module, then you simply change the `rollMode` of the created message (the one containing the roll). This is base foundry, not changed by Requestor. :)

**Comment by MJ-Deepshadow** [comment]
Ok :), (it is indeed a Rollmode from a system, I will try something else :)), thanks for the answer by the way :)
