### ISSUE TITLE
Module page is misformatted

### ISSUE THREAD

**Issue by mowngle** [krbz999/requestor#2]
Hi!

Your github page/readme is wonderfully formatted.  The page on [foundry](https://foundryvtt.com/packages/requestor) looks pretty rough.  I spent 5 or so minutes thinking I needed to include the ``` / ``` script in the macros themselves before realizing that was formatting for something else.  Not sure if there's any way to fix that but it would be nice for newbs such as myself.

**Comment by krbz999** [comment]
Oof. Yeah, that was a mess but thankfully a quick fix. Thanks.
