### ISSUE TITLE
Enhancement Request: Autoclose option for Chat Window

### ISSUE THREAD

**Issue by DeviousHearts** [krbz999/requestor#20]
I feel it would be helpful to make it so that if when both the Popout OR the Chat Requestor button is used, the other disappears as well if both were generated.

**Comment by krbz999** [comment]
This should already be happening. If it does not, then it is a bug and steps to reproduce are required.

**Comment by krbz999** [comment]
Added optional boolean for messages letting users delete the message as soon as any button is clicked (if owner).
