### ISSUE TITLE
When used with Chat Portrait module, img is unhideable [Foundry 11.315]

### ISSUE THREAD

**Issue by Karuna053** [krbz999/requestor#23]
**Modules used:**
- Requestor (11.0.3)
- Chat Portrait (0.9.5)

When both are used together, and the `img` of `Requestor.request()` is set to false, the image box is not hidden and rather displays as a broken portrait box.

![Image](https://github.com/krbz999/requestor/assets/17472074/9411f841-e61e-4981-9faf-1fa0cae84763)

Example code:
`await Requestor.request({
    img: 'true',
    title: "Commit Stunt",
    description: "This is a request.",
    buttonData: [{
        command: async function(){
            return console.log("Log this message!");
        }
    }],
    autoclose: 'false',
    limit: Requestor.LIMIT.ONCE,
});`

**Comment by krbz999** [comment]
In your example code, you are passing `img: 'true'` - is this meant to be `img: false`?

The current implementation checks the module's setting; if no truthy value is provided, the icon will be the default or omitted depending on the single relevant setting.

**Comment by Karuna053** [comment]
I sent the wrong example code, this should be the correct code:

`await Requestor.request({
    img: 'false',
    title: "Commit Stunt",
    description: "This is a request.",
    buttonData: [{
        command: async function(){
            return console.log("Log this message!");
        }
    }],
    autoclose: 'false',
    limit: Requestor.LIMIT.ONCE,
});`

![image](https://github.com/krbz999/requestor/assets/17472074/1dfd7329-5024-4e7c-aa93-1a9868729afb)

I've tried both `img: false` and `img: 'false'`, the about is without quotation and the below is with quotation.

**Comment by krbz999** [comment]
Yep, that tracks. You want `false` and you want to change the module setting.
