### ISSUE TITLE
conditional buttons based on conditions

### ISSUE THREAD

**Issue by slapnutsQ42** [krbz999/requestor#24]
I'm using this for the Lesser Restoration spell for 5e, and trying to find a way to only have the conditions affecting the target show as button options. Currently have it set up that if they select a condition the target doesn't have, to call the macro again. Is there a way to have buttons that only show based on found conditions?
`await Requestor.request
 (
   {
     img:'false',
     title: "Statuses:",
     limit: Requestor.LIMIT.OPTION,
     buttonData:
       [
         {
               label: "Diseased",
               command: async function()
                 {
                   if (typeof game.user.targets.effects.find(effect => effect.name == "Diseased") !== 'undefined')
                        {
                         game.user.targets.effects.find(effect => effect.name == "Diseased").delete();
                         ChatMessage.create({content: 'Diseased has been removed'})
                        } else {
                                 ChatMessage.create({content: 'This status is not active'})
                                 game.macros.find(macro => macro.name == "Lesser Restoration").execute()
                               }
                 },
         },
         {
               label: "Blinded",
               command: async function()
                 {
                   if (typeof game.user.targets.effects.find(effect => effect.name == "Blinded") !== 'undefined')
                        {
                         game.user.targets.effects.find(effect => effect.name == "Blinded").delete();
                         ChatMessage.create({content: 'Blinded has been removed'})
                         console.log(request)
                        } else {
                                 ChatMessage.create({content: 'This status is not active'})
                                 game.macros.find(macro => macro.name == "Lesser Restoration").execute()
                               }
                 },
         },
         {
               label: "Deafened",
               command: async function()
                 {
                   if (typeof game.user.targets.effects.find(effect => effect.name == "Deafened") !== 'undefined')
                        {
                          game.user.targets.effects.find(effect => effect.name == "Deafened").delete();
                          ChatMessage.create({content: 'Deafened has been removed'})
                        } else {
                                 ChatMessage.create({content: 'This status is not active'})
                                 game.macros.find(macro => macro.name == "Lesser Restoration").execute()
                               }
                 },
         },
         {
               label: "Paralyzed",
               command: async function()
                 {
                   if (typeof game.user.targets.effects.find(effect => effect.name == "Paralyzed") !== 'undefined')
                        {
                         game.user.targets.effects.find(effect => effect.name == "Paralyzed").delete();
                         ChatMessage.create({content: 'Paralyzed has been removed'})
                        } else {
                                 ChatMessage.create({content: 'This status is not active'})
                                 game.macros.find(macro => macro.name == "Lesser Restoration").execute()
                               }
                 },
         },
         {
               label: "Poisoned",
               command: async function()
                 {
                   if (typeof game.user.targets.effects.find(effect => effect.name == "Poisoned") !== 'undefined')
                        {
                         game.user.targets.effects.find(effect => effect.name == "Poisoned").delete();
                         ChatMessage.create({content: 'Poisoned has been removed'})
                        } else {
                                 ChatMessage.create({content: 'This status is not active'})
                                 game.macros.find(macro => macro.name == "Lesser Restoration").execute()
                               }
                 },
         },
       ]
    },
 )`

**Comment by krbz999** [comment]
Hi there, Slapnuts. Pop into the discord, and we can figure something out.

**Comment by krbz999** [comment]
Resolved on Discord.
