### ISSUE TITLE
Update module for v12

### ISSUE THREAD

**Issue by AndrewRP8023** [krbz999/requestor#25]
When trying to install the mod, I get this error: 

Error: Unable to load valid module manifest data from "https://github.com/krbz999/requestor/blob/main/module.json" Error parsing module manifest data from https://github.com/krbz999/requestor/blob/main/module.json: Unexpected token '<',"

Foundry Version 12, build 324

**Comment by krbz999** [comment]
Strange to be getting an error when trying to install. However, the module is yet to be updated for v12.
